

<Suggestion>:
    orientation: 'vertical'
    spacing: dp(12)
    padding: [0, dp(12), 0, dp(8)]
    BoxLayout:
        size_hint_y: .99
        padding: [dp(12), dp(4)]
        spacing: dp(8)
        orientation: 'vertical'
        Text:
            text: "What to buy or sell?"
            halign: "center"
            color: app.colors.white
            font_name: app.fonts.headingfont
            font_size: app.fonts.size.s4
            size_hint_y: None
            height: dp(18)
        Text:
            text: "Click on the widgets to trade the coins"
            halign: "center"
            color: app.colors.white
            font_name: app.fonts.bodyfont
            font_size: app.fonts.size.s6
            size_hint_y: None
            height: dp(18)
        BoxLayout:
            size_hint_y: .15
            padding: [dp(62), dp(16)]
            spacing: dp(8)
            orientation: 'vertical'
            BoxLayout:
                size_hint_y: .15
                height: dp(14)
                RoundedButton:
                    text: "refresh"
                    halign: 'center'
                    valign: 'middle'
                    color: app.colors.grey_dark2
                    font_name: app.fonts.subheadingfont
                    font_size: app.fonts.size.s4
                    color: app.colors.white
                    radius: [dp(8)]
                    size_hint_y: .99
                    bcolor: app.colors.thirdlevel_light
                    on_release: root.refresh_()
        BoxLayout:
            ScrollView:
                do_scroll: [False, True]
                size_hint_y: None
                height: self.parent.height
                bar_inactive_color: [0.1,0,0,0]
                bar_active_color: [0.1,0,0,0]
                GridLayout:
                    id: gl_popular
                    cols: 1
                    spacing: dp(4)
                    size_hint_y: None
                    height: self.minimum_height